In [126]:
import pandas as pd
import numpy as np

In [127]:
train = pd.read_csv("M3_train.csv")
test = pd.read_csv("M3_test.csv")

In [128]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [129]:
train[0:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [130]:
train.shape

(891, 12)

In [131]:
test.shape

(418, 11)

In [132]:
test[0:3]

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q

In [133]:
train = train.drop(['PassengerId', 'Name', 'Cabin', 'Ticket'], axis=1)

In [134]:
train.shape

(891, 8)

In [135]:
test.shape

(418, 11)

In [136]:
train[0:3]

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S

In [137]:
train.isna().any()

Survived    False
Pclass      False
Sex         False
Age          True
SibSp       False
Parch       False
Fare        False
Embarked     True
dtype: bool

In [138]:
test.isna().any()

PassengerId    False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare            True
Cabin           True
Embarked       False
dtype: bool

In [139]:
# train 데이터의 null을 찾아서 평균으로 바꾸기
mean1 = train['Age'].mean()
train['Age'] = train['Age'].fillna(mean1)

In [140]:
train.isna().any()

Survived    False
Pclass      False
Sex         False
Age         False
SibSp       False
Parch       False
Fare        False
Embarked     True
dtype: bool

In [141]:
# train 데이터의 null을 찾아서 평균으로 바꾸기
mean2 = test['Age'].mean()
test['Age'] = test['Age'].fillna(mean2)

In [142]:
test.isna().any()

PassengerId    False
Pclass         False
Name           False
Sex            False
Age            False
SibSp          False
Parch          False
Ticket         False
Fare            True
Cabin           True
Embarked       False
dtype: bool

In [143]:
mean3 = train['Fare'].mean()
train['Fare'] = train['Fare'].fillna(mean3)

In [144]:
mean4 = test['Fare'].mean()
test['Fare'] = test['Fare'].fillna(mean4)

In [145]:
train.isna().any()

Survived    False
Pclass      False
Sex         False
Age         False
SibSp       False
Parch       False
Fare        False
Embarked     True
dtype: bool

In [146]:
test.isna().any()

PassengerId    False
Pclass         False
Name           False
Sex            False
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked       False
dtype: bool

In [147]:
mode1 = train['Embarked'].mode()[0]
train['Embarked'] = train['Embarked'].fillna(mode1)

In [148]:
train.isna().any()

Survived    False
Pclass      False
Sex         False
Age         False
SibSp       False
Parch       False
Fare        False
Embarked    False
dtype: bool

In [149]:
# 더미변수처리
train = pd.get_dummies(train, columns=['Sex', 'Embarked'],
                      drop_first = True)
test = pd.get_dummies(test, columns=['Sex', 'Embarked'],
                      drop_first = True)

In [150]:
train[0:3]

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,7.2500,True,False,True
1,1,1,38.0,1,0,71.2833,False,False,False
2,1,3,26.0,0,0,7.9250,False,False,True

In [151]:
train = train.drop(['Sex_male', 'Embarked_Q', 'Embarked_S'], axis=1)
test = test.drop(['Sex_male', 'Embarked_Q', 'Embarked_S'], axis=1)

In [152]:
train[0:3]

   Survived  Pclass   Age  SibSp  Parch     Fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250

In [153]:
train.to_csv('preprocessed_train.csv', index=False)

In [154]:
x_train, y_train = train.drop(['Survived'], axis=1), train.Survived.values

In [157]:
x_train[0:3]

   Pclass   Age  SibSp  Parch     Fare
0       3  22.0      1      0   7.2500
1       1  38.0      1      0  71.2833
2       3  26.0      0      0   7.9250

In [158]:
y_train[0:3]

array([0, 1, 1])

In [161]:
len(x_train)

891

In [162]:
len(y_train)

891

In [163]:
from scipy.stats import pearsonr

In [171]:
corrs = []
for col in x_train.columns:
    corr = pearsonr(x_train[col], y_train)[0]
    print('{} : {}'.format(col, corr))
    corrs.append([col, corr])

Pclass : -0.33848103596101514
Age : -0.06980851528714306
SibSp : -0.03532249888573552
Parch : 0.08162940708348346
Fare : 0.2573065223849624

In [172]:
corrs = pd.DataFrame(corrs, columns = ['columns', 'correlation'])

In [173]:
corrs.sort_values('correlation')

  columns  correlation
0  Pclass    -0.338481
1     Age    -0.069809
2   SibSp    -0.035322
3   Parch     0.081629
4    Fare     0.257307

In [174]:
corrs['correlation'] = corrs['correlation'].apply(np.abs)

In [175]:
corrs.sort_values('correlation')

  columns  correlation
2   SibSp     0.035322
1     Age     0.069809
3   Parch     0.081629
4    Fare     0.257307
0  Pclass     0.338481

In [178]:
corrs.loc[corrs['correlation'].nlargest(3).index]

  columns  correlation
0  Pclass     0.338481
4    Fare     0.257307
3   Parch     0.081629

In [179]:
corrs.loc[corrs['correlation'].nlargest(3).index]['columns'].values

array(['Pclass', 'Fare', 'Parch'], dtype=object)

In [180]:
selected = corrs.loc[corrs['correlation'].nlargest(3).index]['columns'].values

In [181]:
selected

array(['Pclass', 'Fare', 'Parch'], dtype=object)

In [182]:
from sklearn.ensemble import RandomForestClassifier

In [183]:
from sklearn.model_selection import cross_val_score

In [184]:
from sklearn.metrics import accuracy_score

In [189]:
rfc = RandomForestClassifier(random_state=42)
scores = cross_val_score(rfc, x_train, y_train, scoring = 'accuracy',
                        cv = 10)

In [190]:
print(scores)
print('='*20)
print(np.mean(scores))

[0.65555556 0.6741573  0.64044944 0.69662921 0.69662921 0.69662921
 0.76404494 0.68539326 0.69662921 0.74157303]
====================
0.694769038701623

In [191]:
rfc = RandomForestClassifier(random_state=42)
scores = cross_val_score(rfc, x_train[selected], y_train, scoring = 'accuracy',
                        cv = 10)

In [192]:
print(scores)
print('='*20)
print(np.mean(scores))

[0.68888889 0.59550562 0.68539326 0.62921348 0.69662921 0.71910112
 0.6741573  0.79775281 0.75280899 0.74157303]
====================
0.6981023720349564

In [195]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [196]:
bestfeatures = SelectKBest(score_func = chi2, k = 3)

In [197]:
fit = bestfeatures.fit(x_train, y_train)

In [198]:
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(x_train.columns)

In [199]:
dfscores

             0
0    30.873699
1    24.687926
2     2.581865
3    10.097499
4  4518.319091

In [201]:
featureScores = pd.concat([dfcolumns, dfscores], axis=1)
featureScores.columns = ['name', 'score']

In [202]:
featureScores

     name        score
0  Pclass    30.873699
1     Age    24.687926
2   SibSp     2.581865
3   Parch    10.097499
4    Fare  4518.319091

In [203]:
featureScores.nlargest(4, 'score')

     name        score
4    Fare  4518.319091
0  Pclass    30.873699
1     Age    24.687926
3   Parch    10.097499

In [204]:
x_train_chi2 = bestfeatures.fit_transform(x_train, y_train)

In [209]:
rfc1 = RandomForestClassifier(random_state=42)
scores = cross_val_score(rfc1, x_train, y_train, scoring = 'accuracy',
                        cv = 10)
print(scores)
print('='*20)
print(np.mean(scores))

[0.65555556 0.6741573  0.64044944 0.69662921 0.69662921 0.69662921
 0.76404494 0.68539326 0.69662921 0.74157303]
====================
0.694769038701623

In [210]:
rfc2 = RandomForestClassifier(random_state=42)
scores = cross_val_score(rfc2, x_train[selected], y_train, scoring = 'accuracy',
                        cv = 10)
print(scores)
print('='*20)
print(np.mean(scores))

[0.68888889 0.59550562 0.68539326 0.62921348 0.69662921 0.71910112
 0.6741573  0.79775281 0.75280899 0.74157303]
====================
0.6981023720349564

In [211]:
rfc3 = RandomForestClassifier(random_state=42)
scores = cross_val_score(rfc3, x_train_chi2, y_train, scoring = 'accuracy',
                        cv = 10)
print(scores)
print('='*20)
print(np.mean(scores))

[0.63333333 0.62921348 0.60674157 0.66292135 0.68539326 0.69662921
 0.79775281 0.66292135 0.6741573  0.71910112]
====================
0.6768164794007491