In [1]:
import pandas as pd
import numpy as np

In [24]:
df = pd.DataFrame(np.random.randn(5,3),
                  index = range(5),
                  columns = ['one', 'two', 'three',])

In [25]:
df

        one       two     three
0  1.086194 -0.015576 -2.197026
1  0.378388 -0.111729 -0.490000
2  0.510579 -0.298103  1.825307
3  0.556739 -0.041068  0.034114
4  1.361079  1.652485 -0.138217

In [26]:
df.iloc[2:, 1] = np.nan

In [27]:
df

        one       two     three
0  1.086194 -0.015576 -2.197026
1  0.378388 -0.111729 -0.490000
2  0.510579       NaN  1.825307
3  0.556739       NaN  0.034114
4  1.361079       NaN -0.138217

In [28]:
df.iat[-1,0] = np.nan

In [29]:
df

        one       two     three
0  1.086194 -0.015576 -2.197026
1  0.378388 -0.111729 -0.490000
2  0.510579       NaN  1.825307
3  0.556739       NaN  0.034114
4       NaN       NaN -0.138217

In [30]:
df_missing = pd.DataFrame(df.isnull().sum(),
                          columns = ['missing'])
df_missing['percent'] = df_missing['missing'] / float(len(df.index)) * 100

In [31]:
df_missing

       missing  percent
one          1     20.0
two          3     60.0
three        0      0.0

In [32]:
mean = df['one'].mean()

In [33]:
mean

np.float64(0.6329750222761217)

In [34]:
df['one'].fillna(mean, inplace = True)
print(df)

        one       two     three
0  1.086194 -0.015576 -2.197026
1  0.378388 -0.111729 -0.490000
2  0.510579       NaN  1.825307
3  0.556739       NaN  0.034114
4  0.632975       NaN -0.138217

C:\Users\10414\AppData\Local\Temp\ipykernel_23972\94800272.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['one'].fillna(mean, inplace = True)

In [35]:
median = df['one'].median()

df['one'].fillna(mean, inplace = True)
print(df)

        one       two     three
0  1.086194 -0.015576 -2.197026
1  0.378388 -0.111729 -0.490000
2  0.510579       NaN  1.825307
3  0.556739       NaN  0.034114
4  0.632975       NaN -0.138217

C:\Users\10414\AppData\Local\Temp\ipykernel_23972\312850403.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['one'].fillna(mean, inplace = True)

In [39]:
df['two'].fillna(0, inplace = True)
print(df)

        one       two     three
0  1.086194 -0.015576 -2.197026
1  0.378388 -0.111729 -0.490000
2  0.510579  0.000000  1.825307
3  0.556739  0.000000  0.034114
4  0.632975  0.000000 -0.138217

C:\Users\10414\AppData\Local\Temp\ipykernel_23972\3311325873.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['two'].fillna(0, inplace = True)

In [40]:
df = pd.DataFrame(np.random.randint(0,10,
                                    size=(5,3)),
                  index = range(5),
                  columns = ['one', 'two', 'three'])
df = df.astype(str)
df.iat[-1,0] = np.nan
df.iat[-1,1] = np.nan
df.iloc[2:,2] = np.nan
print(df)

   one  two three
0    2    2     6
1    1    7     0
2    0    7   NaN
3    2    3   NaN
4  NaN  NaN   NaN

In [42]:
s = pd.Series([0, 1, np.nan, 3])
print(s)

0    0.0
1    1.0
2    NaN
3    3.0
dtype: float64

In [43]:
print(s.interpolate())

0    0.0
1    1.0
2    2.0
3    3.0
dtype: float64

In [44]:
df['one'].fillna(3, inplace = True)
print(df)

  one  two three
0   2    2     6
1   1    7     0
2   0    7   NaN
3   2    3   NaN
4   3  NaN   NaN

C:\Users\10414\AppData\Local\Temp\ipykernel_23972\4032236002.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['one'].fillna(3, inplace = True)

In [52]:
mode = df['two'].mode()[0]
df['two'].fillna(mode, inplace = True)
print(df)

  one two three
0   2   2     6
1   1   7     0
2   0   7   NaN
3   2   3   NaN
4   3   7   NaN

In [53]:
a = df.dropna(axis = 0)
print(a)

  one two three
0   2   2     6
1   1   7     0

In [54]:
b = df.dropna(axis = 1)
print(b)

  one two
0   2   2
1   1   7
2   0   7
3   2   3
4   3   7

In [56]:
df1 = pd.DataFrame({'employee': ['Bab', 'namki', 'Lisa', 'AAA'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})

In [57]:
df1

  employee        group
0      Bab   Accounting
1    namki  Engineering
2     Lisa  Engineering
3      AAA           HR

In [58]:
df2 = pd.DataFrame({'employee': ['Lisa', 'namki', 'Bab', 'AAA'],
                    'hire_data': [2004, 2008, 2012, 2014]})

In [59]:
df2

  employee  hire_data
0     Lisa       2004
1    namki       2008
2      Bab       2012
3      AAA       2014

In [60]:
df3 = pd.merge(df1, df2)

In [61]:
df3

  employee        group  hire_data
0      Bab   Accounting       2012
1    namki  Engineering       2008
2     Lisa  Engineering       2004
3      AAA           HR       2014

In [62]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor':['AAAAA', 'BBBBB', 'CCCCC']})

In [63]:
df4

         group supervisor
0   Accounting      AAAAA
1  Engineering      BBBBB
2           HR      CCCCC

In [71]:
df5 = pd.merge(df3, df4)

In [72]:
df5

  employee        group  hire_data supervisor
0      Bab   Accounting       2012      AAAAA
1    namki  Engineering       2008      BBBBB
2     Lisa  Engineering       2004      BBBBB
3      AAA           HR       2014      CCCCC

In [67]:
df_ = pd.DataFrame({'name': ['Bab', 'namki', 'Lisa', 'AAA'],
                    'salary': [7000000, 8000000, 12000000, 90000000]})

In [68]:
df_

    name    salary
0    Bab   7000000
1  namki   8000000
2   Lisa  12000000
3    AAA  90000000

In [69]:
pd.merge(df1, df_, left_on = 'employee', right_on = 'name')

  employee        group   name    salary
0      Bab   Accounting    Bab   7000000
1    namki  Engineering  namki   8000000
2     Lisa  Engineering   Lisa  12000000
3      AAA           HR    AAA  90000000

In [73]:
df6 = pd.DataFrame({'name': ['peter', 'paul', 'mary'],
                   'food': ['fish', 'beans', 'bread']},
                   columns = ['name', 'food'])
df7 = pd.DataFrame({'name': ['mary', 'josdph'],
                   'drink': ['wine', 'beer']},
                   columns = ['name', 'drink'])

In [74]:
df6

    name   food
0  peter   fish
1   paul  beans
2   mary  bread

In [75]:
df7

     name drink
0    mary  wine
1  josdph  beer

In [76]:
pd.merge(df6, df7, on = 'name')

   name   food drink
0  mary  bread  wine

In [77]:
pd.merge(df6, df7, on = 'name', how = 'inner')

   name   food drink
0  mary  bread  wine

In [78]:
pd.merge(df6, df7, on = 'name', how = 'left')

    name   food drink
0  peter   fish   NaN
1   paul  beans   NaN
2   mary  bread  wine

In [79]:
pd.merge(df6, df7, on = 'name', how = 'outer')

     name   food drink
0  josdph    NaN  beer
1    mary  bread  wine
2    paul  beans   NaN
3   peter   fish   NaN

In [80]:
df8 = pd.DataFrame({'name': ['peter', 'paul', 'mary'],
                   'food': ['fish', 'beans', 'bread']},
                   columns = ['name', 'food'])
df9 = pd.DataFrame({'name': ['AAA', 'BBB', 'CCC'],
                   'food': ['DDD', 'EEE', 'FFF']},
                   columns = ['name', 'food'])

In [81]:
pd.concat([df8, df9])

    name   food
0  peter   fish
1   paul  beans
2   mary  bread
0    AAA    DDD
1    BBB    EEE
2    CCC    FFF

In [82]:
df = pd.read_csv('M1_data_pepTestCustomers.csv')

In [83]:
df.head()

,id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep
0,ID12101,48,0,0,17546.0,0,1,0,0,0,0,1
1,ID12102,40,1,3,30085.1,1,3,1,0,1,1,0
2,ID12103,51,0,0,16575.4,1,0,1,1,1,0,0
3,ID12104,23,0,3,20375.4,1,3,0,0,1,0,0
4,ID12105,57,0,1,50576.3,1,0,0,1,0,0,0

In [85]:
df.shape

(600, 12)

In [86]:
df1 = df.sample(150)

In [88]:
df1.shape

(150, 12)

In [89]:
df1.head()

,id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep
17,ID12118,46,0,2,41016.0,1,0,0,1,0,1,0
516,ID12617,35,0,3,20262.6,0,0,0,1,0,0,1
441,ID12542,47,1,0,44682.1,1,0,1,1,1,0,0
533,ID12634,60,1,0,29714.4,1,0,1,0,1,1,1
183,ID12284,48,0,0,18516.0,1,2,1,1,1,1,0

In [90]:
df

,id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep
0,ID12101,48,0,0,17546.00,0,1,0,0,0,0,1
1,ID12102,40,1,3,30085.10,1,3,1,0,1,1,0
2,ID12103,51,0,0,16575.40,1,0,1,1,1,0,0
3,ID12104,23,0,3,20375.40,1,3,0,0,1,0,0
4,ID12105,57,0,1,50576.30,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
595,ID12696,61,0,0,47025.00,0,2,1,1,1,1,0
596,ID12697,30,0,0,9672.25,1,0,1,1,1,0,0
597,ID12698,31,0,3,15976.30,1,0,1,1,0,0,1
598,ID12699,29,1,0,14711.80,1,0,0,1,0,1,0
599,ID12700,38,1,3,26671.60,0,0,1,0,1,1,1

In [91]:
df[0:3]

,id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep
0,ID12101,48,0,0,17546.0,0,1,0,0,0,0,1
1,ID12102,40,1,3,30085.1,1,3,1,0,1,1,0
2,ID12103,51,0,0,16575.4,1,0,1,1,1,0,0

In [92]:
test1 = df.drop(['married', 'current_act', 'mortgage'], axis = 1)

In [93]:
test1

          id  age  sex  region    income  children  car  save_act  pep
0    ID12101   48    0       0  17546.00         1    0         0    1
1    ID12102   40    1       3  30085.10         3    1         0    0
2    ID12103   51    0       0  16575.40         0    1         1    0
3    ID12104   23    0       3  20375.40         3    0         0    0
4    ID12105   57    0       1  50576.30         0    0         1    0
..       ...  ...  ...     ...       ...       ...  ...       ...  ...
595  ID12696   61    0       0  47025.00         2    1         1    0
596  ID12697   30    0       0   9672.25         0    1         1    0
597  ID12698   31    0       3  15976.30         0    1         1    1
598  ID12699   29    1       0  14711.80         0    0         1    0
599  ID12700   38    1       3  26671.60         0    1         0    1

[600 rows x 9 columns]