In [1]:
import pandas as pd
import numpy as np

In [2]:
namki = pd.read_csv("M1_data_pepTestCustomers.csv")

In [4]:
namki.head()

,id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep
0,ID12101,48,0,0,17546.0,0,1,0,0,0,0,1
1,ID12102,40,1,3,30085.1,1,3,1,0,1,1,0
2,ID12103,51,0,0,16575.4,1,0,1,1,1,0,0
3,ID12104,23,0,3,20375.4,1,3,0,0,1,0,0
4,ID12105,57,0,1,50576.3,1,0,0,1,0,0,0

In [5]:
# save_act: 저축 예금 계좌 보유 여부
# current_act: 당좌 예금 계좌(또는 자유 입출금 계좌) 보유 여부
# mortage=?, pep= 보헌가입여부

In [6]:
namki[0:2]

,id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep
0,ID12101,48,0,0,17546.0,0,1,0,0,0,0,1
1,ID12102,40,1,3,30085.1,1,3,1,0,1,1,0

In [7]:
namki[0:1]

,id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep
0,ID12101,48,0,0,17546.0,0,1,0,0,0,0,1

In [9]:
namki.shape

(600, 12)

In [10]:
namki['age'].mean()

np.float64(42.395)

In [11]:
namki['income'].mean()

np.float64(27524.031216666666)

In [12]:
m = namki['age'].mean()
s = namki['age'].std()

In [13]:
m

np.float64(42.395)

In [14]:
namki[namki['age'] > m]

,id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep
0,ID12101,48,0,0,17546.0,0,1,0,0,0,0,1
2,ID12103,51,0,0,16575.4,1,0,1,1,1,0,0
4,ID12105,57,0,1,50576.3,1,0,0,1,0,0,0
5,ID12106,57,0,3,37869.6,1,2,0,1,1,0,1
7,ID12108,58,1,3,24946.6,1,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
588,ID12689,58,1,1,49673.6,1,0,0,1,1,0,0
592,ID12693,48,1,3,20268.0,1,0,0,1,1,0,0
593,ID12694,65,1,2,51417.0,1,2,0,1,1,0,1
594,ID12695,59,0,1,30971.8,1,3,1,1,1,1,0
595,ID12696,61,0,0,47025.0,0,2,1,1,1,1,0

In [15]:
namki.groupby('sex')['income'].mean()

sex
0    27831.368233
1    27216.694200
Name: income, dtype: float64

In [20]:
namki.groupby('sex')['income'].mean().sort_values()

sex
1    27216.694200
0    27831.368233
Name: income, dtype: float64

In [22]:
namki.groupby(['region', 'sex'])['income'].mean().sort_values()

region  sex
0       1      26538.128188
3       0      26730.686087
        1      26849.572469
0       0      27166.216031
2       0      28573.271667
        1      28734.249375
1       1      28743.575918
        0      31366.274468
Name: income, dtype: float64

In [24]:
namki.groupby(['age','sex'])['income'].mean().sort_values()

age  sex
18   1      10476.966000
21   1      10570.060000
     0      11161.895000
22   1      12160.287000
19   0      12694.173333
                ...
66   0      45775.114286
63   1      46080.170000
     0      46124.600000
64   1      49731.487500
65   1      49856.375000
Name: income, Length: 99, dtype: float64

In [27]:
grouped = namki.groupby('region')

In [30]:
grouped.get_group(1)

,id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep
4,ID12105,57,0,1,50576.30,1,0,0,1,0,0,0
6,ID12107,22,1,1,8877.07,0,0,0,0,1,0,1
14,ID12115,36,1,1,19474.60,1,0,0,1,1,1,0
29,ID12130,61,1,1,24270.10,1,1,0,0,1,0,1
30,ID12131,61,0,1,22942.90,1,2,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
562,ID12663,57,0,1,50897.60,1,0,0,1,1,0,0
570,ID12671,49,0,1,33665.50,0,3,1,0,1,0,0
583,ID12684,47,0,1,29093.10,0,2,1,1,1,0,0
588,ID12689,58,1,1,49673.60,1,0,0,1,1,0,0
594,ID12695,59,0,1,30971.80,1,3,1,1,1,1,0

In [36]:
grouped['income'].agg([np.sum, np.mean, np.std])

C:\Users\10414\AppData\Local\Temp\ipykernel_5404\2574230428.py:1: FutureWarning: The provided callable <function sum at 0x0000021B9881F420> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grouped['income'].agg([np.sum, np.mean, np.std])
C:\Users\10414\AppData\Local\Temp\ipykernel_5404\2574230428.py:1: FutureWarning: The provided callable <function mean at 0x0000021B98834860> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grouped['income'].agg([np.sum, np.mean, np.std])
C:\Users\10414\AppData\Local\Temp\ipykernel_5404\2574230428.py:1: FutureWarning: The provided callable <function std at 0x0000021B988349A0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  grouped['income'].agg([np.sum, np.mean, np.std])

               sum          mean           std
region
0       7221035.99  26843.999963  13015.863373
1       2882650.12  30027.605417  13699.154297
2       1776694.13  28656.356935  13888.950040
3       4634038.49  26786.349653  11756.638715

In [39]:
def over_income_30000(group):
    return group['income'].mean() > 30000

In [40]:
grouped.filter(over_income_30000)

,id,age,sex,region,income,married,children,car,save_act,current_act,mortgage,pep
4,ID12105,57,0,1,50576.30,1,0,0,1,0,0,0
6,ID12107,22,1,1,8877.07,0,0,0,0,1,0,1
14,ID12115,36,1,1,19474.60,1,0,0,1,1,1,0
29,ID12130,61,1,1,24270.10,1,1,0,0,1,0,1
30,ID12131,61,0,1,22942.90,1,2,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
562,ID12663,57,0,1,50897.60,1,0,0,1,1,0,0
570,ID12671,49,0,1,33665.50,0,3,1,0,1,0,0
583,ID12684,47,0,1,29093.10,0,2,1,1,1,0,0
588,ID12689,58,1,1,49673.60,1,0,0,1,1,0,0
594,ID12695,59,0,1,30971.80,1,3,1,1,1,1,0

In [47]:
pd.pivot_table(namki, columns = 'region')

TypeError: agg function failed [how->mean,dtype->object]

In [43]:
pd.pivot_table(namki, columns = 'region', index = 'id', values = 'income', aggfunc = np.mean)

C:\Users\10414\AppData\Local\Temp\ipykernel_5404\832956641.py:1: FutureWarning: The provided callable <function mean at 0x0000021B98834860> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(namki, columns = 'region', index = 'id', values = 'income', aggfunc = np.mean)

region          0        1   2        3
id
ID12101  17546.00      NaN NaN      NaN
ID12102       NaN      NaN NaN  30085.1
ID12103  16575.40      NaN NaN      NaN
ID12104       NaN      NaN NaN  20375.4
ID12105       NaN  50576.3 NaN      NaN
...           ...      ...  ..      ...
ID12696  47025.00      NaN NaN      NaN
ID12697   9672.25      NaN NaN      NaN
ID12698       NaN      NaN NaN  15976.3
ID12699  14711.80      NaN NaN      NaN
ID12700       NaN      NaN NaN  26671.6

[600 rows x 4 columns]

In [45]:
pd.pivot_table(namki, columns = 'region', index = 'id', values = 'income', aggfunc = np.mean).fillna(0)

C:\Users\10414\AppData\Local\Temp\ipykernel_5404\2503944985.py:1: FutureWarning: The provided callable <function mean at 0x0000021B98834860> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(namki, columns = 'region', index = 'id', values = 'income', aggfunc = np.mean).fillna(0)

region          0        1    2        3
id
ID12101  17546.00      0.0  0.0      0.0
ID12102      0.00      0.0  0.0  30085.1
ID12103  16575.40      0.0  0.0      0.0
ID12104      0.00      0.0  0.0  20375.4
ID12105      0.00  50576.3  0.0      0.0
...           ...      ...  ...      ...
ID12696  47025.00      0.0  0.0      0.0
ID12697   9672.25      0.0  0.0      0.0
ID12698      0.00      0.0  0.0  15976.3
ID12699  14711.80      0.0  0.0      0.0
ID12700      0.00      0.0  0.0  26671.6

[600 rows x 4 columns]